#!/usr/bin/env bash
##FIXME there are a couple of files that have syntax errors so we can not run the input files as *.js which would be ideal

##FILES="barChart.js pieChart.js dashboardTemplater.js pointHierarchyGrouper.js dataDisplayManager.js pointValueDataProvider.js dataPointGroup.js realtimePointValueDataProvider.js dataPointMatcher.js rollupPicker.js dateTimePicker.js select.js  serialChart.js gaugeChart.js simpleDisplay.js historicalPointValueDataProvider.js  statisticsBarChart.js input.js statisticsDataProvider.js statistics.js listView.js timePeriodTypePicker.js"
FILES="classes/*.js"

## the output directory for jsduck to put are documenattion
OUTPUTDIR="../private/docs"
##the title of this classes Documentation 
TITLE="MangoJS"

## The Example configureqation file for js duck
EXAMPLEJSON="examples.json"

## The Video Configuration file for jsduck 
VIDEOJSON="videos.json"

## The welcome screen for are mangojs lib 
WELCOMESCREEN="welcome.html"

## read me files AKA GUIDES IT IS SUPER IMPORTANT THAT THE FILE FOR EACH OF THE GUILDES IS CALLED README.md as it uses markdown to do its work.
READMEFILE="guides.json"

##the Iframes File that includes all of are sources so that one can dit on the fly uising the @example tag in the docs/examples
IFRAMES="eg-iframe.html"

## This is the images assets so that we can include custom images in are docs
IMAGES="assests"

## This is used to make a stuctor hyaricy of are Classes ex: wigets core displays ect 
CATEGORYSJSON="categories.json"

## FIXME make if statement remove the old stuff it is there 
##rm -r $OUTPUTDIR;

## make a new output dir to build in 
mkdir -p $OUTPUTDIR;

## lets copy the class files to make this all much more easy
mkdir classes
cp ../js/mango/*.js classes/

## remove the dang class that is causing error's'

rm classes/deferredAjax.js

## now we just ruin a simple doc command to get a base stuctor going
jsduck -v $FILES -o $OUTPUTDIR --title=$TITLE ;

## Cp the rest of the files to the correct outdir
cp -r assests/ $OUTPUTDIR ;
cp categories.json $OUTPUTDIR ;
cp demoMangoConfig.json $OUTPUTDIR ;
cp eg-iframe.html $OUTPUTDIR ;
cp example.json $OUTPUTDIR ;
cp -r guides/ $OUTPUTDIR ;
cp guides.json $OUTPUTDIR ;
cp videos.json $OUTPUTDIR ;
cp welcome.html $OUTPUTDIR ;
	

## Now we run are final jsdoc to get all the good stuff
jsduck -v $FILES -o $OUTPUTDIR --title=$TITLE --eg-iframe=$IFRAMES --categories=$CATEGORYSJSON --images=$IMAGES --welcome=$WELCOMESCREEN --video=$VIDEOJSON --examples=$EXAMPLEJSON ;

## Cleanup
rm -r classes
## Ishould now link the index.html doc page to the main private folder and or move all the files there.


## for some reason assests/ is not getting copied above WTF 
cp -r assests/ ../private/docs/
